### ISSUE TITLE
Repository status

### ISSUE THREAD

**Issue by JacobCallahan** [RedHatQE/polarizer-vertx#3]
Hi @jstavel, we're checking in to see the status of this repository as part of an organization-level evaluation. Can you let us know the following?

1. Is this being actively developed/maintained?
2. Is this project in active use?
3. If not you, who is the primary contact for this project?

Additionally, since it doesn't have issues enabled, can you answer the same for RedHatQE/reporter?

Thanks!

**Comment by jstavel** [comment]
hi @JacobCallahan this project is a part of our testing stack. We (RHSMQE) test subscription-manager. polarizer-vertx is a base package for a service that sends reports to Polarion.

**Comment by JacobCallahan** [comment]
Thanks for the response!
